# Pentagonal numbers are generated by the formula, 𝑃𝑛=𝑛(3𝑛−1)/2.
# The first ten pentagonal numbers are: 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that 𝑃4+𝑃7=22+70=92=𝑃8. However, their difference, 70−22=48, is not pentagonal.
#
# Find the pair of pentagonal numbers, 𝑃𝑗 and 𝑃𝑘, for which their sum and difference are pentagonal
# and 𝐷=|𝑃𝑘−𝑃𝑗| is minimised; what is the value of 𝐷
from math import isqrt

from timer_utils import timer


def is_pentagonal(x):  # O(1)
    d = 24 * x + 1
    r = int(d**0.5)
    return r * r == d and (1 + r) % 6 == 0


def pent(i):  # O(1)
    return i * (3 * i - 1) // 2


@timer  # O(n^2)
def solution():
    s = set()
    i = 1
    while True:
        pi = pent(i)
        s.add(pi)
        for pj in s:
            if pi - pj in s and is_pentagonal(pj + pi):
                return pi - pj
        i += 1


solution()  # result: 5482660 took: 0.212110s
