# How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
from timer_utils import timer


@timer
def solution(n=100):  # O(n^2)
    primitive = set(range(2, n + 1))

    for a in range(2, int(n**0.5) + 1):  # O(n^0.5 log n)
        p = a * a
        while p <= n:
            primitive.discard(p)
            p *= a

    total = 0

    for r in primitive:  # O(n)
        x = r
        k = 1
        while x <= n:  # O(logr n)
            x *= r
            k += 1

        exponents = {a * b for a in range(1, k) for b in range(2, n + 1)}  # O(nk)

        total += len(exponents)

    return total


solution()  # result: 9183 took: 0.000612s
